# Copyright (c) 2025 Salvo Giangreco
# SPDX-License-Identifier: GPL-3.0-or-later

# UN1CA configuration file for MediaTek devices (mssi)

# Galaxy S23 FE (Exynos) (One UI 8.0)
SOURCE_FIRMWARE="SM-S711B/EUX/350389910895757"
SOURCE_EXTRA_FIRMWARES=()
SOURCE_PLATFORM_SDK_VERSION=36
SOURCE_PRODUCT_FIRST_API_LEVEL=33
SOURCE_BOARD_API_LEVEL=31
SOURCE_HAS_SYSTEM_EXT=false
SOURCE_SUPER_GROUP_NAME="group_basic"

# SEC Product Feature
SOURCE_AUDIO_SUPPORT_ACH_RINGTONE=false
SOURCE_AUDIO_SUPPORT_DUAL_SPEAKER=true
SOURCE_AUDIO_SUPPORT_VIRTUAL_VIBRATION=true
SOURCE_AUTO_BRIGHTNESS_TYPE="5"
SOURCE_DVFS_CONFIG_NAME="dvfs_policy_s5e9925_xx"
SOURCE_ESE_CHIP_VENDOR="GEMALTO"
SOURCE_ESE_COS_NAME="UT8.0U"
SOURCE_FP_SENSOR_CONFIG="google_touch_display_optical,settings=3,aod_transition_animation"
SOURCE_HAS_HW_MDNIE=false
SOURCE_HAS_MASS_CAMERA_APP=true
SOURCE_HAS_QHD_DISPLAY=false
SOURCE_HFR_MODE="2"
SOURCE_HFR_SUPPORTED_REFRESH_RATE="60,120"
SOURCE_HFR_DEFAULT_REFRESH_RATE="120"
SOURCE_HFR_SEAMLESS_BRT="89,91"
SOURCE_HFR_SEAMLESS_LUX="200,2500"
SOURCE_IS_ESIM_SUPPORTED=true
SOURCE_MDNIE_SUPPORTED_MODES="37905"
SOURCE_MDNIE_WEAKNESS_SOLUTION_FUNCTION="0"
SOURCE_MULTI_MIC_MANAGER_VERSION="07020"
SOURCE_SSRM_CONFIG_NAME="siop_r11s_exynos2200"
SOURCE_SUPPORT_CUTOUT_PROTECTION=true

# Galaxy A34 5G (One UI 8.0)
SOURCE_EXTRA_FIRMWARES=("SM-A346B/EUX/351648441234565")
SOURCE_SUPER_GROUP_NAME="main"
